version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - RUST_LOG=info
    depends_on:
      - fluentd
    networks:
      - app-network

  fluentd:
    build:
      context: .
      dockerfile: ./fluentd/Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/app/logs
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
